// @flow

export type PassedConfig = {
  autoCamera?: boolean,
  cameraDuration?: number,
  dotBorderColor?: string,
  dotBorderWidth?: number,
  dotColor?: string,
  dotRadius?: number,
  height?: string,
  id: string,
  lat?: number,
  lng?: number,
  maxZoom?: number,
  minZoom?: number,
  onClick?: Object => void,
  onHover?: Object => void,
  onLoad?: Object => void,
  onMoveEnd?: Object => void,
  scale?: boolean,
  scrollZoom?: boolean,
  static?: boolean,
  theme?: string,
  token: string,
  unit?: 'imperial' | 'metric',
  width?: string,
  zoom?: number,
};

export type Config = {
  apiBase: string,
  autoCamera: boolean,
  cameraDuration: number,
  dotBorderColor: string,
  dotBorderWidth: number,
  dotColor: string,
  dotRadius: number,
  height: string,
  id: string,
  lat: number,
  lng: number,
  maxZoom: number,
  minZoom: number,
  onClick: Object => void,
  onHover: Object => void,
  onLoad: Object => void,
  onMoveEnd: Object => void,
  pops?: Object[],
  popup?: Object,
  scale: boolean,
  scrollZoom: boolean,
  static: boolean,
  theme: string,
  token: string,
  unit: 'imperial' | 'metric',
  width: string,
  zoom: number,
};

export const mergeWithDefaultConfig = (passedConfig: PassedConfig): Config => {
  const defaultConfig: Config = {
    apiBase: 'https://api.inflect.com',
    autoCamera: true,
    cameraDuration: 1000,
    dotBorderColor: '#fff',
    dotBorderWidth: 1,
    dotColor: '#6a7685',
    dotRadius: 6,
    height: 'inherit',
    id: 'inflect-map',
    lat: 28.30438,
    lng: 16.875,
    maxZoom: 24,
    minZoom: 0,
    onClick: () => {},
    onHover: () => {},
    onLoad: () => {},
    onMoveEnd: () => {},
    scale: false,
    scrollZoom: true,
    static: false,
    theme: 'light',
    token: '',
    unit: 'imperial',
    width: 'inherit',
    zoom: 0,
  };

  const config: Config = {
    ...defaultConfig,
    ...passedConfig,
  };

  return config;
};
